import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
    "en-US": {
        FSdailySmoke: "Number of cigarettes smoked daily",
        FSnumberPacked: "Number of cigarettes in a pack",
        FSpricePacked: "Price of a package",
        FSfirstdaySmoke: "How many cigarettes did you smoke today?",
        FSfirstTarget: 'Your first daily target',
        FSsleepingHour: 'How many hours do you sleep a day?',
        FSsend:'send',
        TStargetTime1:'You can smoke every',
        TStargetTime2:'hours acording to the target',
        TDtoday:'Today',
        ABafterBeginning:'After beginning',
        TDABbyInitialVal:'by initial value',
        TDABsmoking:'cigarettes smoked',
        TDABlessSmoked:'you smoked less',
        TDBAmoreSmoked:'you smoked more',
        TDABpacks:'packs of cigarettes smoked',
        TDABspendMoney:'money was spent',
        TDABearnMoney:'earned money',
        TDABlossMoney:'more money was spent',
        MDdidUS:'Did you smoke?',
        MDno:'No',
        MDyes:'Yes',
        TSsetTarget:'Set a new target',
        TSemptyTarget:'your target cannot be empty',
        TScancel:'Cansel',
        TSok:'Ok',
        TSrestart: 'Are you sure it will restart',
        TSyes:'Yes',
        TSno:'No',
        MAareUsmoked:'Are you smoked?'

    },
    en: {
        FSdailySmoke: "Number of cigarettes smoked daily",
        FSnumberPacked: "Number of cigarettes in a pack",
        FSpricePacked: "Price of a package",
        FSfirstdaySmoke: "How many cigarettes did you smoke today?",
        FSfirstTarget: 'Your first daily target',
        FSsleepingHour: 'How many hours do you sleep a day?',
        FSsend:'send',
        TStargetTime1:'You can smoke every',
        TStargetTime2:'hours acording to the target',
        TDtoday:'Today',
        ABafterBeginning:'After beginning',
        TDABbyInitialVal:'by initial value',
        TDABsmoking:'cigarettes smoked',
        TDABlessSmoked:'you smoked less',
        TDABpacks:'packs of cigarettes smoked',
        TDABspendMoney:'money was spent',
        TDABearnMoney:'earned money',
        TDABlossMoney:'more money was spent',
        MDdidUS:'Did you smoke?',
        MDno:'No',
        MDyes:'Yes',
        TSsetTarget:'Set a new target',
        TSemptyTarget:'your target cannot be empty',
        TScancel:'Cansel',
        TSok:'Ok',
        TSrestart: 'Are you sure it will restart',
        TSyes:'Yes',
        TSno:'No',
        MAareUsmoked:'Are you smoked?'
    },
    tr: {
        FSdailySmoke: "Günlük içilen sigara sayısı",
        FSnumberPacked: "Bir paketteki sigara sayısı",
        FSpricePacked: "Paket başına fiyat",
        FSfirstdaySmoke: "Bugün tahminen kaç sigara içtin?",
        FSfirstTarget: 'İlk hafta için günlük hedefiniz',
        FSsleepingHour: 'Günde ortalama kaç saat uyuyorsunuz?',
        FSsend:'gönder',
        TStargetTime1:'Hedefinize göre her',
        TStargetTime2:'saatte bir sigara içebilirsiniz',
        TDtoday:'Bugün',
        ABafterBeginning:'Başlangıçtan sonra',
        TDABbyInitialVal:'Baş. değ. göre',
        TDABsmoking:'sigara içildi',
        TDABlessSmoked:'daha az sigara içtiniz',
        TDABpacks:'paket içildi',
        TDABspendMoney:'para harcandı',
        TDABearnMoney:'kar edildi',
        TDABlossMoney:'daha fazla para harcandı',
        MDdidUS:'Sigara içtiniz mi?',
        MDno:'Hayır',
        MDyes:'Evet',
        TSsetTarget:'Yeni bir hedef belirleyin',
        TSemptyTarget:'hedefiniz boş olamaz',
        TScancel:'Vazgeç',
        TSok:'Tamam',
        TSrestart: 'Yeniden başlatılacak emin misiniz?',
        TSyes:'Evet',
        TSno:'Hayır',
        MAareUsmoked:'Sigara içtiniz mi?'
    }
});